{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolume*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.cobolmlingestdata.name }}-pv*/}}
{{/*  namespace: {{ .Values.cobolmlingestdata.namespace }}*/}}
{{/*spec:*/}}
{{/*  capacity:*/}}
{{/*    storage: {{ .Values.cobolmlingestdata.storage.size }}*/}}
{{/*  volumeMode: Filesystem*/}}
{{/*  accessModes:*/}}
{{/*{{ toYaml .Values.cobolmlingestdata.storage.accessModes | indent 4 }}*/}}
{{/*  persistentVolumeReclaimPolicy: {{ .Values.cobolmlingestdata.storage.reclaimPolicy }}*/}}
{{/*  storageClassName: {{ .Values.cobolmlingestdata.storage.storageClassName }}*/}}
{{/*  csi:*/}}
{{/*    driver: efs.csi.aws.com*/}}
{{/*    volumeHandle: {{ .Values.cobolmlingestdata.storage.volumeHandle }}*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.cobolmlingestdata.name }}-pvc*/}}
{{/*  namespace: {{ .Values.cobolmlingestdata.namespace }}*/}}
{{/*spec:*/}}
{{/*  accessModes:*/}}
{{/*{{ toYaml .Values.cobolmlingestdata.storage.accessModes | indent 4 }}*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: {{ .Values.cobolmlingestdata.storage.size }}*/}}
{{/*  storageClassName: {{ .Values.cobolmlingestdata.storage.storageClassName }}*/}}
{{/*---*/}}
{{/*apiVersion: batch/v1*/}}
{{/*kind: CronJob*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.cobolmlingestdata.name }}-cronjob*/}}
{{/*  namespace: {{ .Values.cobolmlingestdata.namespace }}*/}}
{{/*spec:*/}}
{{/*  schedule: {{ .Values.cobolmlingestdata.schedule }}*/}}
{{/*  concurrencyPolicy: Replace*/}}
{{/*  jobTemplate:*/}}
{{/*    spec:*/}}
{{/*      template:*/}}
{{/*        spec:*/}}
{{/*          restartPolicy: Never*/}}
{{/*          containers:*/}}
{{/*            - name: {{ .Values.cobolmlingestdata.name }}-container*/}}
{{/*              image: "{{ .Values.cobolmlingestdata.image.repository }}:{{ .Values.cobolmlingestdata.image.tag }}"*/}}
{{/*              imagePullPolicy: {{ .Values.cobolmlingestdata.image.pullPolicy }}*/}}
{{/*              volumeMounts:*/}}
{{/*                - name: efs-volume*/}}
{{/*                  mountPath: /output*/}}
{{/*              resources:*/}}
{{/*                requests:*/}}
{{/*                  cpu: "{{ .Values.cobolmlingestdata.resources.requests.cpu }}"*/}}
{{/*                  memory: "{{ .Values.cobolmlingestdata.resources.requests.memory }}"*/}}
{{/*                limits:*/}}
{{/*                  cpu: "{{ .Values.cobolmlingestdata.resources.limits.cpu }}"*/}}
{{/*                  memory: "{{ .Values.cobolmlingestdata.resources.limits.memory }}"*/}}
{{/*          volumes:*/}}
{{/*            - name: efs-volume*/}}
{{/*              persistentVolumeClaim:*/}}
{{/*                claimName: {{ .Values.cobolmlingestdata.name }}-pvc*/}}
{{/*          nodeSelector:*/}}
{{/*            gpu: {{ .Values.cobolmlingestdata.nodeSelector.gpu | quote }}*/}}
