apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cobolmlpostgresql.serviceAccount.name }}
  namespace: {{ .Values.cobolmlpostgresql.serviceAccount.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountNumber }}:role/{{ .Values.cobolmlpostgresql.iamRole.name }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.cobolmlpostgresql.pod.name }}
  namespace: {{ .Values.cobolmlpostgresql.pod.namespace }}
spec:
  serviceAccountName: {{ .Values.cobolmlpostgresql.serviceAccount.name }}
  containers:
  - name: {{ .Values.cobolmlpostgresql.pod.name }}
    image: {{ .Values.cobolmlpostgresql.pod.image }}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: {{ .Values.cobolmlpostgresql.secret.name }}
          key: {{ .Values.cobolmlpostgresql.secret.userKey }}
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.cobolmlpostgresql.secret.name }}
          key: {{ .Values.cobolmlpostgresql.secret.passwordKey }}
    - name: POSTGRES_CONNECTION_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: {{ .Values.cobolmlpostgresql.secret.name }}
          key: {{ .Values.cobolmlpostgresql.secret.connectionEndpointKey }}
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: {{ .Values.cobolmlpostgresql.secretProviderClass.name }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.cobolmlpostgresql.secretProviderClass.name }}
  namespace: {{ .Values.cobolmlpostgresql.serviceAccount.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.cobolmlpostgresql.secret.secretName }}
        objectType: secretsmanager
        jmesPath:
          - path: "username"
            objectAlias: "{{ .Values.cobolmlpostgresql.secret.userKey }}"
          - path: "password"
            objectAlias: "{{ .Values.cobolmlpostgresql.secret.passwordKey }}"
          - path: "connection_endpoint"
            objectAlias: "{{ .Values.cobolmlpostgresql.secret.connectionEndpointKey }}"
  secretObjects:
  - secretName: {{ .Values.cobolmlpostgresql.secret.name }}
    type: Opaque
    data:
    - objectName: "{{ .Values.cobolmlpostgresql.secret.userKey }}"
      key: username
    - objectName: "{{ .Values.cobolmlpostgresql.secret.passwordKey }}"
      key: password
    - objectName: "{{ .Values.cobolmlpostgresql.secret.connectionEndpointKey }}"
      key: connection_endpoint

