apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cobol-0.name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.cobol-0.name }}-pv
  namespace: {{ .Values.cobol-0.name }}
spec:
  capacity:
    storage: {{ .Values.cobol-0.storage.size }}
  volumeMode: Filesystem
  accessModes:
{{ toYaml .Values.cobol-0.storage.accessModes | indent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.cobol-0.storage.reclaimPolicy }}
  storageClassName: {{ .Values.cobol-0.storage.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.cobol-0.storage.volumeHandle }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cobol-0.name }}-pvc
  namespace: {{ .Values.cobol-0.name }}
spec:
  accessModes:
{{ toYaml .Values.cobol-0.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.cobol-0.storage.size }}
  storageClassName: {{ .Values.cobol-0.storage.storageClassName }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.cobol-0.name }}-pod
  namespace: {{ .Values.cobol-0.name }}
spec:
  containers:
    - name: {{ .Values.cobol-0.name }}-container
      image: "{{ .Values.cobol-0.image.repository }}:{{ .Values.cobol-0.image.tag }}"
      imagePullPolicy: {{ .Values.cobol-0.image.pullPolicy }}
      env:
        - name: INPUT_FILE
          value: "{{ .Values.cobol-0.environment.INPUT_FILE }}"
        - name: OUTPUT_FILE
          value: "{{ .Values.cobol-0.environment.OUTPUT_FILE }}"
      volumeMounts:
        - name: efs-volume
          mountPath: /mnt/efs
      resources:
        requests:
          cpu: "{{ .Values.cobol-0.resources.requests.cpu }}"
          memory: "{{ .Values.cobol-0.resources.requests.memory }}"
        limits:
          cpu: "{{ .Values.cobol-0.resources.limits.cpu }}"
          memory: "{{ .Values.cobol-0.resources.limits.memory }}"
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: {{ .Values.cobol-0.name }}-pvc
  nodeSelector:
    {{ .Values.cobol-0.nodeSelector }}