apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.llm.name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.llm.name }}-pv
  namespace: {{ .Values.llm.name }}
spec:
  capacity:
    storage: {{ .Values.global.efs_cobol_0.storage.size }}
  volumeMode: Filesystem
  accessModes:
{{ toYaml .Values.global.efs_cobol_0.storage.accessModes | indent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.global.efs_cobol_0.storage.reclaimPolicy }}
  storageClassName: {{ .Values.global.efs_cobol_0.storage.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.efs_cobol_0.volumeHandle }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.llm.name }}-pvc
  namespace: {{ .Values.llm.name }}
spec:
  accessModes:
{{ toYaml .Values.global.efs_cobol_0.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.global.efs_cobol_0.storage.size }}
  storageClassName: {{ .Values.global.efs_cobol_0.storage.storageClassName }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.llm.name }}-cronjob
  namespace: {{ .Values.llm.name }}
spec:
  schedule: "{{ .Values.llm.schedule }}"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Values.llm.name }}-container
              image: "{{ .Values.llm.image.repository }}:{{ .Values.llm.image.tag }}"
              imagePullPolicy: {{ .Values.llm.image.pullPolicy }}
              env:
                - name: TRANSFORMED_FILE
                  value: "{{ .Values.llm.environment.TRANSFORMED_FILE }}"
                - name: LLM_TRANSFORMED_FILE
                  value: "{{ .Values.llm.environment.LLM_TRANSFORMED_FILE }}"
              volumeMounts:
                - name: efs-volume
                  mountPath: /mnt/efs
              resources:
                requests:
                  cpu: "{{ .Values.llm.resources.requests.cpu }}"
                  memory: "{{ .Values.llm.resources.requests.memory }}"
                limits:
                  cpu: "{{ .Values.llm.resources.limits.cpu }}"
                  memory: "{{ .Values.llm.resources.limits.memory }}"
          volumes:
            - name: efs-volume
              persistentVolumeClaim:
                claimName: {{ .Values.llm.name }}-pvc
          nodeSelector:
            gpu: {{ .Values.llm.nodeSelector.gpu | quote }}
