{{- range .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .ports.servicePort }}
      targetPort: {{ .ports.containerPort }}
      protocol: TCP
{{- end }}
