apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.workercobol0.name }}-efs-pv
  namespace: {{ .Values.workercobol0.namespace }}
spec:
  capacity:
    storage: {{ .Values.global.efs_cobol_0.storage.size }}
  volumeMode: Filesystem
  accessModes:
{{ toYaml .Values.global.efs_cobol_0.storage.accessModes | indent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.global.efs_cobol_0.storage.reclaimPolicy }}
  storageClassName: {{ .Values.global.efs_cobol_0.storage.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.efs_cobol_0.volumeHandle }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workercobol0.name }}-efs-pvc
  namespace: {{ .Values.workercobol0.namespace }}
spec:
  accessModes:
{{ toYaml .Values.global.efs_cobol_0.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.global.efs_cobol_0.storage.size }}
  storageClassName: {{ .Values.global.efs_cobol_0.storage.storageClassName }}

---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.workercobol0.name }}-pod
  namespace: {{ .Values.workercobol0.namespace }}
spec:
  restartPolicy: Always
  containers:
    - name: {{ .Values.workercobol0.name }}
      image: {{ .Values.workercobol0.image.repository }}:{{ .Values.workercobol0.image.tag }}
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 3600; done;"]
      volumeMounts:
        - name: efs-volume
          mountPath: /output
      resources:
        requests:
          cpu: "{{ .Values.workercobol0.resources.requests.cpu }}"
          memory: "{{ .Values.workercobol0.resources.requests.memory }}"
        limits:
          cpu: "{{ .Values.workercobol0.resources.limits.cpu }}"
          memory: "{{ .Values.workercobol0.resources.limits.memory }}"
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: {{ .Values.workercobol0.name }}-efs-pvc
  nodeSelector:
    gpu: {{ .Values.workercobol0.nodeSelector.gpu | quote }}
