apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.workercobolml.name }}-efs-pv
  namespace: {{ .Values.workercobolml.namespace }}
spec:
  capacity:
    storage: {{ .Values.global.efs_cobol_ml.storage.size }}
  volumeMode: Filesystem
  accessModes:
{{ toYaml .Values.global.efs_cobol_ml.storage.accessModes | indent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.global.efs_cobol_ml.storage.reclaimPolicy }}
  storageClassName: {{ .Values.global.efs_cobol_ml.storage.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.efs_cobol_ml.volumeHandle }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workercobolml.name }}-efs-pvc
  namespace: {{ .Values.workercobolml.namespace }}
spec:
  accessModes:
{{ toYaml .Values.global.efs_cobol_ml.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.global.efs_cobol_ml.storage.size }}
  storageClassName: {{ .Values.global.efs_cobol_ml.storage.storageClassName }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.workercobolml.name }}-s3-pv
  namespace: {{ .Values.workercobolml.namespace }}
spec:
  capacity:
    storage: {{ .Values.global.s3.storage.size }}
  volumeMode: Filesystem
  accessModes:
{{ toYaml .Values.global.s3.storage.accessModes | indent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.global.s3.storage.reclaimPolicy }}
  storageClassName: {{ .Values.global.s3.storage.storageClassName }}
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-{{ .Values.workercobolml.name }}-logs
    volumeAttributes:
      bucketName: {{ .Values.global.s3.bucketName }}
      mounter: s3fs
      authType: "pod"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workercobolml.name }}-s3-pvc
  namespace: {{ .Values.workercobolml.namespace }}
spec:
  accessModes:
{{ toYaml .Values.global.s3.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.global.s3.storage.size }}
  storageClassName: {{ .Values.global.s3.storage.storageClassName }}
  volumeName: {{ .Values.workercobolml.name }}-s3-pv

---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.workercobolml.name }}-pod
  namespace: {{ .Values.workercobolml.namespace }}
spec:
  serviceAccountName: {{ .Values.cobolmlpostgresql.name }}-sa
  restartPolicy: Always
  containers:
    - name: {{ .Values.workercobolml.name }}
      image: {{ .Values.workercobolml.image.repository }}:{{ .Values.workercobolml.image.tag }}
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 3600; done;"]
      volumeMounts:
        - name: efs-volume
          mountPath: /output
        - name: s3-volume
          mountPath: /logs
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      env:
        - name: POSTGRES_CONNECTION_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.name }}
              key: {{ .Values.cobolmlpostgresql.secret.connectionEndpointKey }}
        - name: POSTGRES_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.name }}
              key: {{ .Values.cobolmlpostgresql.secret.databaseNameKey }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.name }}
              key: {{ .Values.cobolmlpostgresql.secret.passwordKey }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secret.name }}
              key: {{ .Values.cobolmlpostgresql.secret.userKey }}
      resources:
        requests:
          cpu: "{{ .Values.workercobolml.resources.requests.cpu }}"
          memory: "{{ .Values.workercobolml.resources.requests.memory }}"
        limits:
          cpu: "{{ .Values.workercobolml.resources.limits.cpu }}"
          memory: "{{ .Values.workercobolml.resources.limits.memory }}"
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: {{ .Values.workercobolml.name }}-efs-pvc
    - name: s3-volume
      persistentVolumeClaim:
        claimName: {{ .Values.workercobolml.name }}-s3-pvc
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ .Values.cobolmlpostgresql.secretProviderClass.name }}
  nodeSelector:
    gpu: {{ .Values.workercobolml.nodeSelector.gpu | quote }}
