deepseek:
  name: deepseek

  replicaCount: 1
  image:
    repository: "704855531002.dkr.ecr.us-east-1.amazonaws.com/eks_cobol/deepseek"
    tag: "latest"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 11434

  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: "1"
      memory: "2Gi"
      nvidia.com/gpu: 1
