#microservices:
#  - name: rfp-response-backend
#    image:
#      repository: 040848615584.dkr.ecr.us-east-1.amazonaws.com/ai_ml_shared_infra/rfp_response_backend
#      tag: 2025-01-20T19-39-44Z
#    namespace: rfp-response-backend
#    ports:
#      containerPort: 5000
#      servicePort: 80
#    replicas: 1
