cobol0:
  name: cobol-0

  image:
    repository: "704855531002.dkr.ecr.us-east-1.amazonaws.com/eks_cobol/cobol_0"
    tag: "2"
    pullPolicy: Always

  nodeSelector:
    gpu: 'false'

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  schedule: "0 * * * *"

  storage:
    size: 5Gi
    accessModes:
      - ReadWriteMany
    reclaimPolicy: Retain
    storageClassName: efs-sc
    volumeHandle: fs-033cec616c35aff95:/

  environment:
    INPUT_FILE: /mnt/efs/input/orders.csv
    OUTPUT_FILE: /mnt/efs/output/transformed_orders.txt

cobolmlingestdata:
  name: cobol-ml-ingest-data
  namespace: cobol-ml

  image:
    repository: "704855531002.dkr.ecr.us-east-1.amazonaws.com/eks_cobol/cobol_ml_cobol_ingestion"
    tag: "4"
    pullPolicy: Always

  nodeSelector:
    gpu: 'false'

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  schedule: "5 * * * *"

  storage:
    size: 5Gi
    accessModes:
      - ReadWriteMany
    reclaimPolicy: Retain
    storageClassName: efs-sc
    volumeHandle: fs-0b11c021faf9e5922:/

cobolmlrawdata:
  name: cobol-ml-raw-data
  namespace: cobol-ml

  image:
    repository: "704855531002.dkr.ecr.us-east-1.amazonaws.com/eks_cobol/cobol_ml_raw_generator"
    tag: "4"
    pullPolicy: Always

  nodeSelector:
    gpu: 'false'

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  schedule: "0,10,20,30,40,50 * * * *"

  storage:
    size: 5Gi
    accessModes:
      - ReadWriteMany
    reclaimPolicy: Retain
    storageClassName: efs-sc
    volumeHandle: fs-0b11c021faf9e5922:/

deepseek:
  name: deepseek

  replicaCount: 1
  image:
    repository: "704855531002.dkr.ecr.us-east-1.amazonaws.com/eks_cobol/deepseek"
    tag: "latest"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 11434

  nodeSelector:
    gpu: 'true'

  resources:
    limits:
      gpu: 1
    requests:
      cpu: "1"
      memory: "2Gi"
      gpu: 1

llm:
  name: llm

  image:
    repository: "704855531002.dkr.ecr.us-east-1.amazonaws.com/eks_cobol/llm"
    tag: "1"
    pullPolicy: Always

  nodeSelector:
    gpu: "false"

  schedule: "0 * * * *"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  storage:
    size: 5Gi
    accessModes:
      - ReadWriteMany
    reclaimPolicy: Retain
    storageClassName: efs-sc
    volumeHandle: fs-033cec616c35aff95:/

  environment:
    TRANSFORMED_FILE: "/mnt/efs/output/transformed_orders.txt"
    LLM_TRANSFORMED_FILE: "/mnt/efs/output/llm_transformed_orders.txt"

cobolmlpostgresql:
  enabled: true
  serviceAccount:
    name: cobolml-postgres-sa
    namespace: cobol-ml
  pod:
    name: cobolml-postgres-pod
    namespace: cobol-ml
    image: ubuntu:latest
  secret:
    name: cobolml-postgres-secret
    secretName: rds!cluster-cc1fc0e8-a7ca-4430-b2df-5f94dd24e692
    userKey: username
    passwordKey: password
  secretProviderClass:
    name: aws-secrets-provider

